ls:
    spring/**/*:
        .dir: regex:^[a-z0-9]+$
        .kt: PascalCase
    spring-test/**/*:
        .dir: regex:^[a-z0-9]+$
        .kt: PascalCase

ignore:
    - .git
    - .github
    - .vscode
    - __MACOSX
    - "**/__MACOSX"
    - .DS_Store
    - "**/.DS_Store"
    - .agents
    - "**/.agents"
    - .idea
    - "**/.idea"
    - .gradle
    - "**/.gradle"
    - .kotlin
    - "**/.kotlin"
    - build
    - "**/build"
